const char CONFIG_HTML[] =
  "<!DOCTYPE HTML>"
  "<html>"
  "<head>"
  "<meta name = \"viewport\" content = \"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">"
  "<title>Konfiguration</title>"
  "<style>"
  "  body { background-color: #808080; font-family: Courier; Color: #40FF00; }"
  "</style>"
  "</head>"
  "<body>"
  "<FORM action=\"/\" method=\"post\">"
  "<pre>"
  "{_|_|_|    _|                      _|                          _|    _|                          _|_|  _|                                            _|      _|                    <br>"  
  " _|    _|        _|_|_|  _|_|_|    _|    _|_|_|  _|    _|      _|  _|      _|_|    _|_|_|      _|            _|_|_|  _|    _|  _|  _|_|    _|_|_|  _|_|_|_|        _|_|    _|_|_|  <br>"  
  " _|    _|  _|  _|_|      _|    _|  _|  _|    _|  _|    _|      _|_|      _|    _|  _|    _|  _|_|_|_|  _|  _|    _|  _|    _|  _|_|      _|    _|    _|      _|  _|    _|  _|    _|<br>"  
  " _|    _|  _|      _|_|  _|    _|  _|  _|    _|  _|    _|      _|  _|    _|    _|  _|    _|    _|      _|  _|    _|  _|    _|  _|        _|    _|    _|      _|  _|    _|  _|    _|<br>"  
  " _|_|_|    _|  _|_|_|    _|_|_|    _|    _|_|_|    _|_|_|      _|    _|    _|_|    _|    _|    _|      _|    _|_|_|    _|_|_|  _|          _|_|_|      _|_|  _|    _|_|    _|    _|<br>"
  "                         _|                            _|                                                        _|                                                                <br>"  
  "                         _|                        _|_|                                                      _|_|                                                                  <br>"  
  "<br>"
  "Access Point:"
  "<INPUT type=\"text\" name=\"AP\"><BR>"
  "Password:    "
  "<INPUT type=\"password\" name=\"PASSWORD\"><BR>"
  "Zeile 1:     "
  "<INPUT type=\"text\" name=\"HOST0\" value=\"\"><INPUT type=\"text\" name=\"URL0\" value=\"\"><BR>"
  "Zeile 2:     "
  "<INPUT type=\"text\" name=\"HOST1\" value=\"\"><INPUT type=\"text\" name=\"URL1\" value=\"\"><BR>"
  "Zeile 3:     "
  "<INPUT type=\"text\" name=\"HOST2\" value=\"\"><INPUT type=\"text\" name=\"URL2\" value=\"\"><BR>"
  "Zeile 4:     "
  "<INPUT type=\"text\" name=\"HOST3\" value=\"\"><INPUT type=\"text\" name=\"URL3\" value=\"\"><BR>"
  "<INPUT type=\"submit\" value=\"OK\">"
  "</pre>"
  "</FORM>"
  "</body>"
  "</html>";
